// Merges the Wrangler-generated `Env` (worker-configuration.d.ts, regenerated by
// `npm run cf-typegen`) into `CloudflareEnv`, which @opennextjs/cloudflare's
// getCloudflareContext() returns.
export {};

declare global {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface CloudflareEnv extends Env {}
}
